@extends('layouts.admin')

@section('title', 'Workforce — '.__('app.name'))

@section('content')
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">People operations</p><h1 class="h2 mb-0">Workforce</h1></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#payoutModal">Run payout</button></div>
    @include('admin.workforce.employees')
    <ul class="nav nav-tabs mb-4" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#leave">Leave</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#attendance">Attendance</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#payouts">Payouts</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#scorecards">Scorecards</button></li></ul>
    <div class="tab-content"><div class="tab-pane fade show active" id="leave"><div class="card content-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th></th></tr></thead><tbody>@forelse($leaveRequests as $leave)<tr><td>{{ $leave->user->name }}</td><td>{{ $leave->leave_type }}</td><td>{{ $leave->starts_on->format('d M') }} – {{ $leave->ends_on->format('d M Y') }}</td><td>{{ $leave->days }}</td><td><span class="badge text-bg-light">{{ $leave->status->value }}</span></td><td class="text-end">@if($leave->status === \App\Enums\LeaveStatus::Pending)<div class="d-flex gap-1 justify-content-end"><form method="POST" action="{{ route('admin.leave-requests.review', $leave) }}" data-ajax>@csrf<input type="hidden" name="status" value="APPROVED"><button class="btn btn-sm btn-success">Approve</button></form><form method="POST" action="{{ route('admin.leave-requests.review', $leave) }}" data-ajax>@csrf<input type="hidden" name="status" value="REJECTED"><button class="btn btn-sm btn-outline-danger">Reject</button></form></div>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">No leave requests.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="tab-pane fade" id="attendance"><div class="card content-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Employee</th><th>Date</th><th>Check in</th><th>Check out</th><th>Hours</th></tr></thead><tbody>@forelse($attendance as $record)<tr><td>{{ $record->user->name }}</td><td>{{ $record->attendance_date->format('d M Y') }}</td><td>{{ $record->checked_in_at?->format('h:i A') ?? '—' }}</td><td>{{ $record->checked_out_at?->format('h:i A') ?? '—' }}</td><td>{{ number_format($record->worked_minutes / 60, 2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">No attendance data.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="tab-pane fade" id="payouts"><div class="row g-3 mb-4">@forelse($payoutCycles as $cycle)<div class="col-lg-6"><div class="card content-card"><div class="card-body"><div class="d-flex justify-content-between"><div><h2 class="h5">{{ $cycle->cycle_number }}</h2><div class="text-secondary">{{ $cycle->starts_on->format('d M') }} – {{ $cycle->ends_on->format('d M Y') }}</div></div><span class="badge text-bg-primary align-self-start">{{ $cycle->status->value }}</span></div><hr><div class="d-flex justify-content-between"><span>{{ $cycle->lines_count }} statements</span><strong>₹{{ number_format((float)$cycle->net_total, 2) }}</strong></div></div></div></div>@empty<div class="col-12 text-secondary">No payout cycles.</div>@endforelse</div><h2 class="h5">Open disputes</h2><div class="vstack gap-3">@forelse($payoutDisputes as $dispute)<div class="card content-card"><div class="card-body"><div class="d-flex justify-content-between"><strong>{{ $dispute->user->name }}</strong><span>{{ $dispute->payoutLine->cycle->cycle_number }}</span></div><p class="my-2">{{ $dispute->reason }}</p><form method="POST" action="{{ route('admin.payout-disputes.resolve', $dispute) }}" data-ajax class="row g-2">@csrf<div class="col-md-3"><select class="form-select" name="status"><option value="RESOLVED">Resolved</option><option value="REJECTED">Rejected</option></select></div><div class="col-md-7"><input class="form-control" name="resolution" placeholder="Resolution" required></div><div class="col-md-2"><button class="btn btn-primary w-100">Close</button></div></form></div></div>@empty<div class="text-secondary">No open disputes.</div>@endforelse</div></div>
        <div class="tab-pane fade" id="scorecards"><div class="row g-3">@forelse($scorecards as $scorecard)<div class="col-md-6 col-xl-4"><div class="card content-card h-100"><div class="card-body"><div class="display-6 fw-bold text-primary">{{ number_format((float)$scorecard->score, 1) }}</div><h2 class="h5">{{ $scorecard->user->name }}</h2><div class="small text-secondary">{{ $scorecard->completed_jobs }} jobs · {{ $scorecard->average_rating }} rating · {{ $scorecard->sla_percentage }}% SLA</div></div></div></div>@empty<div class="col-12 text-secondary">Scorecards are generated nightly.</div>@endforelse</div></div></div>
    <div class="modal fade" id="payoutModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.payout-cycles.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Generate payout cycle</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body vstack gap-3"><div><label class="form-label">Cycle</label><select class="form-select" name="type"><option>WEEKLY</option><option>MONTHLY</option><option>DAILY</option></select></div><div class="row g-2"><div class="col"><label class="form-label">Starts</label><input class="form-control" type="date" name="starts_on" required></div><div class="col"><label class="form-label">Ends</label><input class="form-control" type="date" name="ends_on" required></div></div><div><label class="form-label">Hourly rate</label><input class="form-control" type="number" step="0.01" name="base_hourly_rate" value="0" required></div><div><label class="form-label">Per-job rate</label><input class="form-control" type="number" step="0.01" name="per_job_rate" value="0" required></div><div><label class="form-label">High-rating incentive</label><input class="form-control" type="number" step="0.01" name="rating_incentive" value="0"></div><div><label class="form-label">Low-rating penalty</label><input class="form-control" type="number" step="0.01" name="low_rating_penalty" value="0"></div><div><label class="form-label">Fixed deduction</label><input class="form-control" type="number" step="0.01" name="fixed_deduction" value="0"></div></div><div class="modal-footer"><button class="btn btn-primary">Generate statements</button></div></form></div></div></div>
    @include('admin.workforce.statements')
@endsection
