@extends('layouts.admin')

@section('title', 'Customer feedback — '.__('app.name'))

@section('content')
<div class="d-flex flex-wrap align-items-end justify-content-between gap-3 mb-4"><div><p class="admin-eyebrow text-primary mb-1">Service quality</p><h1 class="h2 mb-1">Customer feedback</h1><p class="text-secondary mb-0">See every rating, investigate poor experiences, and record the resolution.</p></div><a class="btn btn-outline-primary" href="{{ route('admin.jobs.index') }}"><i class="bi bi-kanban me-1"></i>Job pipeline</a></div>

<div class="row g-3 mb-4">
    <div class="col-sm-6 col-xl-3"><div class="card content-card h-100"><div class="card-body p-4"><div class="small fw-semibold text-secondary text-uppercase">Reviews</div><div class="display-6 fw-bold">{{ $totalCount }}</div><div class="small text-secondary">All submitted service ratings</div></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card content-card h-100"><div class="card-body p-4"><div class="small fw-semibold text-secondary text-uppercase">30-day rating</div><div class="display-6 fw-bold text-warning">{{ $averageRating === null ? '—' : number_format((float) $averageRating, 1) }} <i class="bi bi-star-fill fs-4"></i></div><div class="small text-secondary">Average customer score</div></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card content-card h-100"><div class="card-body p-4"><div class="small fw-semibold text-secondary text-uppercase">Needs attention</div><div class="display-6 fw-bold text-danger">{{ $escalatedCount }}</div><div class="small text-secondary">Escalated feedback</div></div></div></div>
    <div class="col-sm-6 col-xl-3"><div class="card content-card h-100"><div class="card-body p-4"><div class="small fw-semibold text-secondary text-uppercase">Resolved</div><div class="display-6 fw-bold text-success">{{ $resolvedCount }}</div><div class="small text-secondary">Closed follow-ups</div></div></div></div>
</div>

<section class="card content-card">
    <div class="card-header bg-white border-0 px-4 py-4 d-flex flex-wrap justify-content-between align-items-end gap-3"><div><p class="admin-eyebrow text-primary mb-1">Feedback register</p><h2 class="h5 mb-0">Customer voice</h2></div><form method="GET" class="d-flex align-items-center gap-2"><label class="small text-secondary" for="feedback-status">Status</label><select class="form-select form-select-sm" id="feedback-status" name="status" onchange="this.form.submit()"><option value="">All</option><option value="ESCALATED" @selected(request('status') === 'ESCALATED')>Escalated</option><option value="OPEN" @selected(request('status') === 'OPEN')>Open</option><option value="RESOLVED" @selected(request('status') === 'RESOLVED')>Resolved</option></select></form></div>
    <div class="table-responsive"><table class="table table-hover align-middle mb-0" data-rich-table="server"><thead><tr><th>Customer / job</th><th>Rating</th><th>Feedback</th><th>Submitted</th><th>Status</th><th data-unsortable>Follow-up</th></tr></thead><tbody>
        @forelse($feedback as $item)
            <tr><td><strong>{{ $item->customer?->name ?? 'Customer' }}</strong><div class="small text-secondary">{{ $item->customer?->phone }}</div>@if($item->job)<a class="small" href="{{ route('admin.jobs.show', $item->job) }}">{{ $item->job->job_number }}</a>@else<span class="small text-secondary">Job unavailable</span>@endif<div class="small text-secondary">{{ $item->job?->service_type }}</div></td><td><span class="fw-bold {{ $item->rating <= 2 ? 'text-danger' : ($item->rating >= 4 ? 'text-success' : 'text-warning') }}">{{ $item->rating }} / 5 <i class="bi bi-star-fill"></i></span></td><td style="min-width: 16rem; max-width: 24rem"><div class="fw-medium">{{ $item->comment ?: 'No written comment' }}</div>@if($item->resolution)<div class="small text-success mt-2"><i class="bi bi-check-circle me-1"></i>{{ $item->resolution }}</div>@endif</td><td class="text-secondary small">{{ $item->created_at->format('d M Y') }}<div>{{ $item->created_at->format('h:i A') }}</div></td><td><span class="badge rounded-pill {{ $item->status === 'ESCALATED' ? 'text-bg-danger' : ($item->status === 'RESOLVED' ? 'text-bg-success' : 'text-bg-warning') }}">{{ str($item->status)->headline() }}</span></td><td style="min-width: 15rem">@if($item->status === 'RESOLVED')<div class="small text-secondary mb-2">Closed by {{ $item->resolver?->name ?? 'team' }} {{ $item->resolved_at?->diffForHumans() }}</div><form method="POST" action="{{ route('admin.feedback.review', $item) }}" data-ajax>@csrf<input type="hidden" name="status" value="ESCALATED"><button class="btn btn-sm btn-outline-danger" type="submit">Reopen follow-up</button></form>@else<form method="POST" action="{{ route('admin.feedback.review', $item) }}" data-ajax class="vstack gap-2">@csrf<input type="hidden" name="status" value="RESOLVED"><textarea class="form-control form-control-sm" name="resolution" rows="2" placeholder="How did you resolve this?" required></textarea><button class="btn btn-sm btn-success" type="submit"><i class="bi bi-check2-circle me-1"></i>Resolve</button></form>@endif</td></tr>
        @empty<tr><td colspan="6" class="text-center text-secondary py-5">No customer feedback has been submitted yet.</td></tr>@endforelse
    </tbody></table></div>
    <div class="card-body border-top px-4">{{ $feedback->links() }}</div>
</section>
@endsection
