@extends('layouts.admin')

@section('title', 'Analytics — '.__('app.name'))

@section('content')
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Insights & operations</p><h1 class="h2 mb-0">Analytics</h1></div><div class="btn-group"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#scheduleModal">Schedule report</button><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#reportModal">Generate report</button><button class="btn btn-primary" data-confirm-ajax data-method="POST" data-url="{{ route('admin.backups.store') }}" data-title="Create tenant backup?" data-text="The encrypted application storage will receive a compressed data export.">Back up now</button></div></div>
    <div class="row g-4 mb-4">@foreach($metrics as $section => $values)<div class="col-md-6 col-xl-4"><div class="card content-card h-100"><div class="card-body"><h2 class="h5 text-capitalize">{{ $section }}</h2>@foreach($values as $label => $value)<div class="d-flex justify-content-between border-top py-2"><span class="text-secondary">{{ str($label)->headline() }}</span><strong>{{ is_float($value) ? number_format($value, 2) : number_format($value) }}</strong></div>@endforeach</div></div></div>@endforeach</div>
    <div class="row g-4"><div class="col-xl-7"><div class="card content-card"><div class="card-header bg-white fw-semibold">Generated reports</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Type</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>@forelse($reports as $report)<tr><td>{{ str($report->report_type)->headline() }}</td><td>{{ $report->status->value }}</td><td>{{ $report->created_at->format('d M Y, h:i A') }}</td><td class="text-end">@if($report->status === \App\Enums\ReportStatus::Completed)<a class="btn btn-sm btn-outline-primary" href="{{ route('admin.reports.download', $report) }}">Download</a>@endif</td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-4">No reports.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-5"><div class="card content-card mb-4"><div class="card-header bg-white fw-semibold">Schedules</div><div class="list-group list-group-flush">@forelse($schedules as $schedule)<div class="list-group-item"><strong>{{ $schedule->name }}</strong><div class="small text-secondary">{{ $schedule->frequency->value }} · next {{ $schedule->next_run_at?->diffForHumans() }}</div></div>@empty<div class="p-4 text-secondary">No report schedules.</div>@endforelse</div></div><div class="card content-card"><div class="card-header bg-white fw-semibold">Backups</div><div class="list-group list-group-flush">@forelse($backups as $backup)<div class="list-group-item d-flex justify-content-between align-items-center"><div><strong>{{ $backup->created_at->format('d M Y, h:i A') }}</strong><div class="small text-secondary">{{ $backup->status->value }}</div></div>@if($backup->status === \App\Enums\ReportStatus::Completed)<a class="btn btn-sm btn-outline-primary" href="{{ route('admin.backups.download', $backup) }}">Download</a>@endif</div>@empty<div class="p-4 text-secondary">No backups.</div>@endforelse</div></div></div></div>
    <div class="modal fade" id="reportModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.reports.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Generate report</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Report</label><select class="form-select" name="report_type">@foreach(array_keys($metrics) as $type)<option value="{{ $type }}">{{ str($type)->headline() }}</option>@endforeach</select></div><div class="modal-footer"><button class="btn btn-primary">Generate PDF</button></div></form></div></div></div>
    <div class="modal fade" id="scheduleModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.report-schedules.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Schedule report</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body vstack gap-3"><div><label class="form-label">Name</label><input class="form-control" name="name" required></div><div><label class="form-label">Report type</label><select class="form-select" name="report_type">@foreach(array_keys($metrics) as $type)<option value="{{ $type }}">{{ str($type)->headline() }}</option>@endforeach</select></div><div><label class="form-label">Frequency</label><select class="form-select" name="frequency">@foreach($frequencies as $frequency)<option value="{{ $frequency->value }}">{{ $frequency->value }}</option>@endforeach</select></div><div><label class="form-label">Recipients</label><input class="form-control" type="email" name="recipients[]" required></div><input type="hidden" name="is_active" value="1"></div><div class="modal-footer"><button class="btn btn-primary">Save schedule</button></div></form></div></div></div>
@endsection
