@extends('layouts.admin')

@section('title', 'Inventory — '.__('app.name'))

@section('content')
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Commerce</p><h1 class="h2 mb-0">Inventory</h1></div><div class="btn-group"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#taxModal">GST profile</button><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#locationModal">New location</button><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#movementModal">Stock movement</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#itemModal">New item</button></div></div>
    <div class="card content-card mb-4"><div class="card-body"><form class="input-group" method="GET"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search SKU or item"><button class="btn btn-outline-primary">Search</button></form></div></div>
    <div class="card content-card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>SKU</th><th>Item</th><th>Price</th><th>Available stock</th><th>Used on jobs</th><th>Reorder</th><th>Status</th><th data-unsortable></th></tr></thead><tbody>
        @forelse($items as $item)@php($stock = (float)($item->incoming_quantity ?? 0) - (float)($item->outgoing_quantity ?? 0))<tr><td class="font-monospace">{{ $item->sku }}</td><td class="fw-semibold">{{ $item->name }}<div class="small text-secondary">{{ $item->unit }}</div></td><td>₹{{ number_format((float)$item->sale_price, 2) }}</td><td><span class="fw-semibold {{ $stock <= (float)$item->reorder_level ? 'text-danger' : 'text-success' }}">{{ number_format($stock, 3) }}</span><div class="small text-secondary">{{ $item->unit }} available</div></td><td>{{ number_format((float)($item->job_consumed_quantity ?? 0), 3) }} {{ $item->unit }}</td><td>{{ $item->reorder_level }}</td><td><span class="badge text-bg-{{ $item->is_active ? 'success' : 'secondary' }}">{{ $item->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-danger" data-confirm-ajax data-url="{{ route('admin.inventory.destroy', $item) }}" data-title="Delete item?">Delete</button></td></tr>@empty<tr><td colspan="8" class="text-center text-secondary py-5">No inventory items.</td></tr>@endforelse
    </tbody></table></div><div class="card-body border-top">{{ $items->links() }}</div></div>

    <div class="modal fade" id="itemModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('admin.inventory.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">New inventory item</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
        <div class="col-md-4"><label class="form-label">SKU</label><input class="form-control" name="sku" required></div><div class="col-md-8"><label class="form-label">Name</label><input class="form-control" name="name" required></div>
        <div class="col-md-4"><label class="form-label">Unit</label><input class="form-control" name="unit" value="PCS" required></div><div class="col-md-4"><label class="form-label">Unit cost</label><input class="form-control" type="number" step="0.01" min="0" name="unit_cost" value="0" required></div><div class="col-md-4"><label class="form-label">Sale price</label><input class="form-control" type="number" step="0.01" min="0" name="sale_price" value="0" required></div>
        <div class="col-md-4"><label class="form-label">Reorder level</label><input class="form-control" type="number" step="0.001" min="0" name="reorder_level" value="0" required></div><div class="col-md-4"><label class="form-label">HSN</label><input class="form-control" name="hsn_code"></div><div class="col-md-4"><label class="form-label">Tax profile</label><select class="form-select" name="tax_profile_id"><option value="">None</option>@foreach($taxProfiles as $tax)<option value="{{ $tax->id }}">{{ $tax->name }} ({{ $tax->tax_rate }}%)</option>@endforeach</select></div>
        <input type="hidden" name="is_active" value="1"><input type="hidden" name="track_serials" value="0"><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"></textarea></div>
    </div></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal" type="button">Cancel</button><button class="btn btn-primary">Save item</button></div></form></div></div></div>

    <div class="modal fade" id="locationModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.stock-locations.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">New stock location</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body vstack gap-3"><div><label class="form-label">Code</label><input class="form-control" name="code" required></div><div><label class="form-label">Name</label><input class="form-control" name="name" required></div><div><label class="form-label">Type</label><select class="form-select" name="type">@foreach($locationTypes as $type)<option value="{{ $type->value }}">{{ str($type->value)->headline() }}</option>@endforeach</select></div><div><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="">None</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div><div><label class="form-label">Custodian</label><select class="form-select" name="custodian_id"><option value="">None</option>@foreach($technicians as $technician)<option value="{{ $technician->id }}">{{ $technician->name }}</option>@endforeach</select></div></div><div class="modal-footer"><button class="btn btn-primary">Save location</button></div></form></div></div></div>

    <div class="modal fade" id="movementModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('admin.stock-movements.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Record stock movement</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Item</label><select class="form-select" name="inventory_item_id" required>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->sku }} — {{ $item->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Type</label><select class="form-select" name="type">@foreach($movementTypes as $type)<option value="{{ $type->value }}">{{ str($type->value)->headline() }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">From</label><select class="form-select" name="from_location_id"><option value="">External / none</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">To</label><select class="form-select" name="to_location_id"><option value="">Consumed / none</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Quantity</label><input class="form-control" type="number" step="0.001" min="0.001" name="quantity" required></div><div class="col-md-4"><label class="form-label">Unit cost</label><input class="form-control" type="number" step="0.01" min="0" name="unit_cost" value="0" required></div><div class="col-md-4"><label class="form-label">Reference</label><input class="form-control" name="reference"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Record movement</button></div></form></div></div></div>
    <div class="modal fade" id="taxModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.tax-profiles.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Create GST profile</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Name</label><input class="form-control" name="name" placeholder="GST 18%" required></div><div class="col-md-6"><label class="form-label">GSTIN</label><input class="form-control" name="gstin"></div><div class="col-md-3"><label class="form-label">HSN</label><input class="form-control" name="hsn_code"></div><div class="col-md-3"><label class="form-label">SAC</label><input class="form-control" name="sac_code"></div><div class="col-md-6"><label class="form-label">Tax rate %</label><input class="form-control" type="number" step="0.01" min="0" max="100" name="tax_rate" value="18" required></div><div class="col-md-6 d-flex align-items-end"><div class="form-check mb-2"><input type="hidden" name="is_default" value="0"><input class="form-check-input" type="checkbox" name="is_default" value="1" id="defaultTax"><label class="form-check-label" for="defaultTax">Default profile</label></div></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save profile</button></div></form></div></div></div>
@endsection
