@extends('layouts.admin')

@section('title', $order->order_number.' — Purchases')

@section('content')
    <a class="text-decoration-none small" href="{{ route('admin.purchases.index') }}"><i class="bi bi-arrow-left me-1"></i> All purchases</a>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mt-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Purchase order</p><h1 class="h2 mb-1">{{ $order->order_number }}</h1><div class="text-secondary">{{ $order->vendor?->name }} · Ordered {{ $order->ordered_on?->format('d M Y') }}</div></div><span class="badge fs-6 rounded-pill text-bg-{{ $order->status === 'RECEIVED' ? 'success' : 'warning' }}">{{ str($order->status)->headline() }}</span></div>
    <div class="row g-4"><div class="col-xl-8"><div class="card content-card mb-4"><div class="card-header bg-transparent border-0 px-4 pt-4"><h2 class="h5 mb-0">Ordered parts</h2></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Item</th><th>Qty</th><th>Unit cost</th><th>Tax</th><th>Total</th></tr></thead><tbody>@foreach ($order->lines as $line)<tr><td class="fw-semibold">{{ $line->inventoryItem?->name }}<div class="small text-secondary">{{ $line->inventoryItem?->sku }}</div></td><td>{{ number_format((float) $line->quantity, 3) }}</td><td>₹{{ number_format((float) $line->unit_cost, 2) }}</td><td>{{ number_format((float) $line->tax_rate, 2) }}%</td><td class="fw-semibold">₹{{ number_format((float) $line->line_total, 2) }}</td></tr>@endforeach</tbody></table></div><div class="card-body border-top"><div class="row justify-content-end"><div class="col-md-5"><div class="d-flex justify-content-between mb-1"><span class="text-secondary">Subtotal</span><strong>₹{{ number_format((float) $order->subtotal, 2) }}</strong></div><div class="d-flex justify-content-between mb-1"><span class="text-secondary">Input tax</span><strong>₹{{ number_format((float) $order->tax_total, 2) }}</strong></div><div class="d-flex justify-content-between fs-5 border-top pt-2"><span>Total payable</span><strong>₹{{ number_format((float) $order->grand_total, 2) }}</strong></div></div></div></div></div>
        <div class="card content-card"><div class="card-body p-4"><h2 class="h5">Payments to vendor</h2>@forelse ($order->payments as $payment)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $payment->entry_date?->format('d M Y') }} · {{ $payment->payment_method }}<small class="d-block text-secondary">{{ $payment->reference ?: $payment->entry_number }}</small></span><strong>₹{{ number_format((float) $payment->amount, 2) }}</strong></div>@empty<div class="text-secondary">No payments recorded.</div>@endforelse<div class="d-flex justify-content-between pt-3"><strong>Outstanding</strong><strong class="text-primary">₹{{ number_format(max(0, (float) $order->grand_total - $order->payments->sum('amount')), 2) }}</strong></div></div></div>
    </div><div class="col-xl-4"><div class="card content-card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Supplier &amp; receipt</h2><dl class="row mb-0"><dt class="col-5 text-secondary fw-normal">Vendor</dt><dd class="col-7 fw-semibold">{{ $order->vendor?->name }}</dd><dt class="col-5 text-secondary fw-normal">Contact</dt><dd class="col-7">{{ $order->vendor?->phone ?: '—' }}</dd><dt class="col-5 text-secondary fw-normal">GSTIN</dt><dd class="col-7">{{ $order->vendor?->gstin ?: '—' }}</dd><dt class="col-5 text-secondary fw-normal">Warehouse</dt><dd class="col-7">{{ $order->stockLocation?->name }}</dd><dt class="col-5 text-secondary fw-normal">Supplier bill</dt><dd class="col-7">{{ $order->supplier_invoice_number ?: '—' }}</dd><dt class="col-5 text-secondary fw-normal">Due date</dt><dd class="col-7">{{ $order->due_on?->format('d M Y') ?: '—' }}</dd><dt class="col-5 text-secondary fw-normal">Received</dt><dd class="col-7">{{ $order->received_at?->format('d M Y, h:i A') ?: 'Awaiting delivery' }}</dd></dl>@if ($order->notes)<div class="small bg-light rounded-3 p-3 mt-3">{{ $order->notes }}</div>@endif</div></div>
        @if ($order->status === 'ORDERED')<div class="card content-card border-primary"><div class="card-body p-4"><h2 class="h5">Goods arrived?</h2><p class="text-secondary small">Confirm the physical delivery. This adds all order lines to {{ $order->stockLocation?->name }} inventory once.</p><form method="POST" action="{{ route('admin.purchases.receive', $order) }}" data-ajax>@csrf<div class="mb-3"><label class="form-label">Supplier invoice number</label><input class="form-control" name="supplier_invoice_number" value="{{ $order->supplier_invoice_number }}" maxlength="100"></div><button class="btn btn-primary w-100" type="submit"><i class="bi bi-box-arrow-in-down me-1"></i> Receive goods into stock</button></form></div></div>@else<div class="alert alert-success"><i class="bi bi-check-circle me-1"></i> Stock was added on {{ $order->received_at?->format('d M Y') }}.</div>@endif
        @if ($order->status === 'RECEIVED' && (float) $order->grand_total > (float) $order->payments->sum('amount'))<div class="card content-card mt-4"><div class="card-body p-4"><h2 class="h5 mb-2">Pay supplier</h2><p class="text-secondary small">Record a payment against this bill. Remaining: ₹{{ number_format((float) $order->grand_total - $order->payments->sum('amount'), 2) }}.</p><form method="POST" action="{{ route('admin.account-entries.store') }}" data-ajax>@csrf<input type="hidden" name="type" value="PURCHASE_PAYMENT"><input type="hidden" name="purchase_order_id" value="{{ $order->id }}"><div class="row g-3"><div class="col-6"><label class="form-label">Amount ₹</label><input class="form-control" type="number" step="0.01" min="0.01" max="{{ number_format((float) $order->grand_total - $order->payments->sum('amount'), 2, '.', '') }}" name="amount" required></div><div class="col-6"><label class="form-label">Date</label><input class="form-control" type="date" name="entry_date" value="{{ today()->toDateString() }}" required></div><div class="col-6"><label class="form-label">Method</label><select class="form-select" name="payment_method"><option value="BANK">Bank</option><option value="UPI">UPI</option><option value="CASH">Cash</option></select></div><div class="col-6"><label class="form-label">Reference</label><input class="form-control" name="reference" maxlength="120"></div><div class="col-12"><button class="btn btn-primary w-100" type="submit">Record vendor payment</button></div></div></form></div></div>@endif
        @if ($order->status === 'RECEIVED')<a class="btn btn-outline-primary w-100 mt-3" href="{{ route('admin.accounts.index') }}">View accounts &amp; P/L</a>@endif
    </div></div>
@endsection
