@extends('layouts.admin')

@section('title', 'Warranty — '.__('app.name'))

@section('content')
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
        <div><p class="text-primary fw-semibold mb-1">Coverage</p><h1 class="h2 mb-0">Warranties, claims & AMC</h1></div>
        <div class="btn-group"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#amcModal">New AMC</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#warrantyModal">Register warranty</button></div>
    </div>

    <div class="row g-4 mb-4">
        @forelse($warranties as $warranty)
            <div class="col-lg-6"><article class="card content-card h-100"><div class="card-body p-4">
                <div class="d-flex justify-content-between gap-3"><div><h2 class="h5">{{ $warranty->asset->brand }} {{ $warranty->asset->model }}</h2><div class="text-secondary">{{ $warranty->customer->name }}</div></div><span class="badge text-bg-success align-self-start">{{ $warranty->status }}</span></div>
                <dl class="row small mt-4 mb-3"><dt class="col-5">Coverage</dt><dd class="col-7">{{ str($warranty->type->value)->lower()->headline() }}</dd><dt class="col-5">Policy</dt><dd class="col-7">{{ $warranty->policy_number ?? '—' }}</dd><dt class="col-5">Expires</dt><dd class="col-7">{{ $warranty->ends_on->format('d M Y') }}</dd></dl>
                <div class="d-flex gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.warranties.certificate', $warranty) }}">Certificate</a><button class="btn btn-sm btn-outline-danger" data-bs-toggle="collapse" data-bs-target="#claim-{{ $warranty->id }}">New claim</button></div>
                <div class="collapse mt-3" id="claim-{{ $warranty->id }}"><form method="POST" action="{{ route('admin.warranty-claims.store') }}" data-ajax class="border rounded p-3">@csrf<input type="hidden" name="warranty_id" value="{{ $warranty->id }}"><textarea class="form-control mb-2" name="issue" placeholder="Describe the warranty issue" required></textarea><button class="btn btn-danger w-100">Submit claim</button></form></div>
                @if($warranty->claims->isNotEmpty())
                    <hr><div class="vstack gap-3">@foreach($warranty->claims as $claim)<div class="border rounded p-3"><div class="d-flex justify-content-between mb-2"><strong>{{ $claim->claim_number }}</strong><span class="badge text-bg-light">{{ str($claim->status->value)->lower()->headline() }}</span></div><form method="POST" action="{{ route('admin.warranty-claims.review', $claim) }}" data-ajax class="row g-2">@csrf<div class="col-md-5"><select class="form-select form-select-sm" name="status">@foreach($claimStatuses as $status)<option value="{{ $status->value }}" @selected($claim->status === $status)>{{ str($status->value)->lower()->headline() }}</option>@endforeach</select></div><div class="col-md-4"><input class="form-control form-control-sm" type="number" step="0.01" min="0" name="approved_amount" value="{{ $claim->approved_amount }}" placeholder="Approved ₹"></div><div class="col-md-3"><button class="btn btn-sm btn-outline-primary w-100">Update</button></div><div class="col-12"><input class="form-control form-control-sm" name="decision_notes" value="{{ $claim->decision_notes }}" placeholder="Decision notes"></div></form></div>@endforeach</div>
                @endif
            </div></article></div>
        @empty
            <div class="col-12"><div class="card content-card"><div class="card-body text-center text-secondary py-5">No warranties registered.</div></div></div>
        @endforelse
    </div>
    <div class="mb-4">{{ $warranties->links() }}</div>

    <div class="card content-card mb-4"><div class="card-body p-4"><h2 class="h5 mb-3">Annual maintenance contracts</h2><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Contract</th><th>Customer</th><th>Asset</th><th>Visits</th><th>Value</th><th>Valid until</th></tr></thead><tbody>@forelse($amcContracts as $contract)<tr><td>{{ $contract->contract_number }}</td><td>{{ $contract->customer->name }}</td><td>{{ $contract->asset ? $contract->asset->brand.' '.$contract->asset->model : 'All assets' }}</td><td>{{ $contract->used_visits }}/{{ $contract->included_visits }}</td><td>₹{{ number_format((float) $contract->amount, 2) }}</td><td>{{ $contract->ends_on->format('d M Y') }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No AMC contracts yet.</td></tr>@endforelse</tbody></table></div></div></div>

    <div class="modal fade" id="warrantyModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('admin.warranties.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Register warranty</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Customer</label><select class="form-select" name="customer_id" required>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Asset</label><select class="form-select" name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->customer->name }} — {{ $asset->brand }} {{ $asset->model }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Type</label><select class="form-select" name="type">@foreach($warrantyTypes as $type)<option value="{{ $type->value }}">{{ str($type->value)->lower()->headline() }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Provider</label><input class="form-control" name="provider"></div><div class="col-md-4"><label class="form-label">Policy number</label><input class="form-control" name="policy_number"></div><div class="col-md-6"><label class="form-label">Starts</label><input class="form-control" type="date" name="starts_on" required></div><div class="col-md-6"><label class="form-label">Ends</label><input class="form-control" type="date" name="ends_on" required></div></div></div><div class="modal-footer"><button class="btn btn-primary">Register</button></div></form></div></div></div>

    <div class="modal fade" id="amcModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="POST" action="{{ route('admin.amc-contracts.store') }}" data-ajax>@csrf<div class="modal-header"><h2 class="h5 modal-title">Create AMC contract</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Customer</label><select class="form-select" name="customer_id" required>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Asset</label><select class="form-select" name="asset_id"><option value="">All customer assets</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->customer->name }} — {{ $asset->brand }} {{ $asset->model }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Starts</label><input class="form-control" type="date" name="starts_on" required></div><div class="col-md-4"><label class="form-label">Ends</label><input class="form-control" type="date" name="ends_on" required></div><div class="col-md-4"><label class="form-label">Included visits</label><input class="form-control" type="number" min="1" name="included_visits" value="4" required></div><div class="col-md-4"><label class="form-label">Contract value</label><input class="form-control" type="number" step="0.01" min="0" name="amount" required></div><div class="col-md-8"><label class="form-label">Terms</label><input class="form-control" name="terms"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Create contract</button></div></form></div></div></div>
@endsection
